language: java


sudo: false

install: true
script:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    recipients:
      - s9153104109@gmail.com
    on_success: never
    on_failure: always
env:
  global:
    - CODECOV_TOKEN="1ef021bc-8c77-4210-b147-07cf8707d50c"